name: martontoth
favicon: null
layout_spectrum: 0.595747851068154
typography_spectrum: 0.33000857569277287
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.09691523760557175
  lightness: 0.35229699057526886
  saturation: 0.9041030018124729
  rhythmicContrast: 0.9930579115170985
purpose: []
